version: '3'

services:
  library-books:
    build:
      context: .
      dockerfile: library-api-books/Dockerfile
    volumes:
      - "./library-api-books/target:/app"
    env_file:
      - enviromental/library-books.env
    command: [/scripts/launch.sh, "0", /app/pg-0.0.1-SNAPSHOT.jar]
  
  library-publishing-houses:
    build:
      context: .
      dockerfile: library-api-publishing-houses/Dockerfile
    volumes:
      - "./library-api-publishing-houses/target:/app"
    env_file:
      - enviromental/library-publishing-houses.env
    command: [/scripts/launch.sh, "20", /app/pg-0.0.1-SNAPSHOT.jar]
    depends_on:
      - library-books
  
  library-gateway:
    build:
      context: .
      dockerfile: library-api-gateway/Dockerfile
    volumes:
      - "./library-api-gateway/target:/app"
    env_file:
      - enviromental/library-gateway.env
    command: [/scripts/launch.sh, "40", /app/pg-0.0.1-SNAPSHOT.jar]
    ports:
      - 8084:8084
    depends_on:
      - library-publishing-houses

  library-angular:
    build:
      context: library-javascript
      dockerfile: Dockerfile
    env_file:
      - enviromental/library-front.env
    ports:
      - "8085:80"
    depends_on:
      - library-gateway
    command: [/scripts/launch.sh, "15"]

  npm:
    image: node:18
    volumes:
      - ./library-javascript:/app
    command: bash /app/build.sh
