version: '3'

services:
  books-db:
    image: postgres:16.1
    env_file:
      - ./enviromental/books-db.env
    volumes:
      - books-data:/var/lib/postgresql/data

  publishing-houses-db:
    image: postgres:16.1
    env_file:
      - ./enviromental/publishing-houses-db.env
    volumes:
      - publishing-houses-data:/var/lib/postgresql/data

  library-books:
    build:
      context: .
      dockerfile: library-api-books/Dockerfile
    volumes:
      - "./library-api-books/target:/app"
    env_file:
      - enviromental/library-books.env
    command: [/scripts/launch.sh, "5", /app/pg-0.0.1-SNAPSHOT.jar]
    depends_on:
      - books-db
  
  library-publishing-houses:
    build:
      context: .
      dockerfile: library-api-publishing-houses/Dockerfile
    volumes:
      - "./library-api-publishing-houses/target:/app"
    env_file:
      - enviromental/library-publishing-houses.env
    command: [/scripts/launch.sh, "30", /app/pg-0.0.1-SNAPSHOT.jar]
    depends_on:
      - publishing-houses-db
      - library-books
  
  library-gateway:
    build:
      context: .
      dockerfile: library-api-gateway/Dockerfile
    volumes:
      - "./library-api-gateway/target:/app"
    env_file:
      - enviromental/library-gateway.env
    command: [/scripts/launch.sh, "50", /app/pg-0.0.1-SNAPSHOT.jar]
    ports:
      - 8084:8084
    depends_on:
      - library-publishing-houses

  library-angular:
    build:
      context: library-javascript
      dockerfile: Dockerfile
    env_file:
      - enviromental/library-front.env
    ports:
      - "8085:80"
    depends_on:
      - library-gateway
    volumes:
      - ./library-javascript/dist/library-view/:/usr/share/nginx/html/
    command: [/scripts/launch.sh, "70"]
    
  npm:
    image: node:18
    volumes:
      - ./library-javascript:/app
    command: bash /app/build.sh

volumes:
  publishing-houses-data:
  books-data: