version: '3'

services:
  library-books:
    build:
      context: .
      dockerfile: library-api-books/Dockerfile
    volumes:
      - "./library-api-books/target:/app"
    env_file:
      - enviromental/library-books.env
    command: [/scripts/launch.sh, "0", /app/pg-0.0.1-SNAPSHOT.jar]
    ports:
      - 8081:8081
  
  library-publishing-houses:
    build:
      context: .
      dockerfile: library-api-publishing-houses/Dockerfile
    volumes:
      - "./library-api-publishing-houses/target:/app"
    env_file:
      - enviromental/library-publishing-houses.env
    command: [/scripts/launch.sh, "10", /app/pg-0.0.1-SNAPSHOT.jar]
    ports:
      - 8082:8082
    depends_on:
      - library-books
