### Get all books

GET http://localhost:8080/api/books

### Get single book

GET http://localhost:8080/api/books/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

### Get single book, not existing

GET http://localhost:8080/api/books/525d3e7b-bb1f-4c13-bf17-926d1a12eeee

### Get publishing houses

GET http://localhost:8080/api/publishing-houses

### Get single publishing house

GET http://localhost:8080/api/publishing-houses/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Get single publishing house, not existing

GET http://localhost:8080/api/publishing-houses/f5875513-bf7b-4ae1-b8a5-5b70a1b90eee

### Get publishing house's books

GET http://localhost:8080/api/publishing-houses/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/books

### Get publishing house's books, publishing house not existing

GET http://localhost:8080/api/publishing-houses/f5875513-bf7b-4ae1-b8a5-5b70a1b90eee/books

