version: "3.3"
services:
  npm:
    build:
      context: ./dockerfiles
      dockerfile: npm.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
